config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  
  resources :users do
    member do
      get :followings, :followers
    end
  end
  
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false }
  has_secure_password
  
  has_many :microposts
  #followしている人
  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  #特定のuserがfollowしている人
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower

  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  
  def followed_count
    follower_relationships.count
  end
  
  def following_count
    following_relationships.count
  end
   
  
  # 投稿を取得
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
    store_location
    flash[:danger] = "Please Log in."
    redirect_to login_url
    end
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!!"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user
  
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end
  
  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invaild email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build if logged_in?
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page]).per(5)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only: [:show, :followings, :followers]
  def show
   @microposts = @user.microposts
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Samle App!"
      redirect_to @user
    else
      render 'new'
    end
  end
    
  def edit
    @user = current_user
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to current_user
    else
      render 'edit'
    end
  end
  
  def followings
    @title = "followings"
    @followers = @user.following_users
    render 'followers'
  end
  
  def followers
    @title = "followers"
    @followers = @user.follower_users
  end
  
    
  private
  def user_params
    params.require(:user).permit(:name, :area, :profile, :email, :password, :password_confirmation)
  end
  
  def set_user
   @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
  def store_location
    session[:fowarding_url] = request.url if request.get?
  end
end
    

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end
    

app/views/layouts/_header.html.erb
<div class="container-fluid">
<header class="navbar navbar-fixed-top navbar-inverse">
 <!--  <div class="container"> -->
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li><%= link_to "Edit", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>Microposts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container-fluid">

      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="row user-body">

       <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    投稿 <%= time_ago_in_words(micropost.created_at) %> 前
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "削除してもよろしいですか？" } %>
    <% end %>
  </span>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains
      <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li  class="error_list"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= link_to "#{current_user.name}", user_path(current_user.id) %></h1>
<div class="patial-user-info">
  <span><%= link_to "プロフィール表示", current_user %></span>
  <span><%= pluralize(current_user.microposts.count, "post") %></span>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3
      <%= page_entries_info @feed_items %>
      <%= render 'shared/feed' %>
      <%= paginate @feed_items %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_follow.html.erb
<section>
  <%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
    <div>
      <%= hidden_field_tag :followed_id, @user.id %>
    </div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
  <% end %>
</section>

app/views/users/_follow_form.html.erb
<div>
  <% if current_user != @user %>
    <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<section>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
      
      <!-- エラーメッセージの表示 -->
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      
      <%= f.text_field :name %>
      
      <%= f.label :email %>
      
      <%= f.text_field :email %>
      
      <%= f.label :password %>
      
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
      
      <% end %>
    </div>
  </div>
</section>

app/views/users/_unfollow.html.erb
<section>
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id), 
html: { method: :delete }, 
remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>
</section>

app/views/users/edit.html.erb
<% @profile_title = "プロフィール編集" %>
  <h1 class="edit-title"><%= @profile_title %></h1>
<div class="row">
  <div class="edit-wrapper">
  <div class="col-md-9 col-md-offset-2">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>  
      
      <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
          <label for="microposts_name" class="col-sm-12 control-label">名前</label>
          <%= f.text_field :name, :class => "form-control", placeholder: "山田　太郎" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
          <label for="microposts_area" class="col-sm-12 control-label">居住地</label>
          <% options = ["北海道", "東北", "関東", "中部", "近畿", "中国", "四国", "九州", "沖縄"] %>
          <%= f.select :area, options, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
          <label for="microposts_profile" class="col-sm-12 control-label">自己紹介</label>
          <%= f.text_area :profile, :class => "form-control", :rows => 6, placeholder: "ここに自己紹介を10文字以上で入力してください" %>
        </div>
      </div>

      <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <label for="microposts_email" class="col-sm-12 control-label">メールアドレス</label>
          <%= f.text_field :email, placeholder: "yamada@sample.com" %>
      </div>

      <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
          <label for="microposts_password" class="col-sm-12 control-label">パスワード</label>
          <%= f.password_field :password, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
          <label for="microposts_password_confirmation" class="col-sm-12 control-label">パスワード確認</label>
          <%= f.password_field :password_confirmation, :class => "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
          <%= f.submit "更新する", :class => "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1><%= @title %> / <%= @followers.count %>user</h1>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <div>
        <%= gravatar_for @user %>
      </div>
      <div class="profile-info">
        <h1><%= link_to "#{@user.name}", user_path %></h1>
        <div>
          <ul>
            <li>Address <%= @user.area %></li>
            <li><%= link_to " Follower #{ @user.followed_count }", followers_user_path %></li>
            <li><%= link_to " Follow #{ @user.following_count }", followings_user_path %></li>
          </ul>
        </div>
      </div>
    </section>
    
    <% if logged_in? %>
      <% if @user == current_user %>
        <div class="button-panel">
        <%= link_to "Profile Edit" , edit_user_path(current_user), class: "btn btn-block btn-info", id: "profile-button" %>
        </div>
      <% else %>
      <% end %>
    <% else %>
      <div class="button-panel">
      <%= link_to "Log in" , login_path, class: "btn btn-block btn-info", id: "profile-button" %>
      </div>
    <% end %>
  </aside>

  <div class="col-md-8">
    <div class="followers">
      <div class="panel-body">
        <div class="alt-table-responsive">
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th class="col-xs-1 col-ms-1 col-md-1 col-lg-1">id</th>
                <th class="col-xs-3 col-ms-3 col-md-3 col-lg-3">Name</th>
                <th class="col-xs-2 col-ms-2 col-md-2 col-lg-2">Area</th>
                <th class="col-xs-6 col-ms-6 col-md-6 col-lg-6">Profile</th>
              </tr>
            </thead>
            <tbody>
            <% @followers.each do |f| %>
              <tr>
                <th><span><%= f.id %></span></th>
                <td><span class="message-body"><%= link_to "#{f.name}", user_path(f.id) %></span></td>
                <td><span class="message-body"><%= f.area %></span></td>
                <td><span class="message-body"><%= f.profile %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/users/new.html.erb
<div class="row form-wrapper">
  <div>
    <h1>Sign up</h1>
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %> 

      <div class="form-item">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-item">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-item">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-item">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="button-panel">
        <%= f.submit "アカウントを作成", class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <div>
        <%= gravatar_for @user %>
      </div>
      <div class="profile-info">
        <h1><%= link_to "#{@user.name}", user_path %></h1>
        <div>
          <ul>
            <li>Address <%= @user.area %></li>
            <li><%= link_to " Follower #{ @user.followed_count }", followers_user_path %></li>
            <li><%= link_to " Follow #{ @user.following_count }", followings_user_path %></li>
          </ul>
        </div>
      </div>
    </section>
    
    <% if logged_in? %>
      <%= render 'follow_form' if logged_in? %>
      <% if @user == current_user %>
        <div class="button-panel">
        <%= link_to "プロフィールの編集" , edit_user_path(current_user), class: "btn btn-block btn btn-primary", id: "profile-button" %>
        </div>
      <% else %>
      <% end %>
    <% else %>
      <div class="button-panel">
      <%= link_to "Log in" , login_path, class: "btn btn-block btn-info", id: "profile-button" %>
      </div>
    <% end %>
  </aside>

  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>My Micropost (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>